language: cpp

dist: trusty
sudo: false

compiler:
  - gcc

git:
  depth: 3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - gcc-6
    - gcc-mingw-w64-i686
    - g++-mingw-w64-i686
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64

before_install:
  - export CXX="g++-6"
  - export CC="gcc-6"
  - export LD="g++-6"

before_script:
  - mkdir FMU/build
  - mkdir FMU/buildDebug
  - mkdir FMU/build32
  - mkdir FMU/build64

script:
  - cd FMU/buildDebug
  - cmake -DTests=on -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - ./tests/runUnitTests
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make
  - ./tests/runUnitTests
  - cd ../build64
  - cmake -DCrossCompile64=ON -DCMAKE_BUILD_TYPE=Release ../
  - make
  - mv libFMI.dll libFMI64.dll
  - cd ../build32
  - cmake -DCrossCompile32=ON -DCMAKE_BUILD_TYPE=Release ../
  - make
  - mv libFMI.dll libFMI32.dll
  - cd ../../

notifications:
  email: false

os:
  - linux

deploy:
  provider: releases
  api-key: "e9ce95182cc7c302f0f74029411c7d912a6afcfa "
  file:
    - "FMU/build/libFMI.so"
    - "FMU/build32/libFMI32.dll"
    - "FMU/build64/libFMI64.dll"
  skip_cleanup: true
  on:
    tags: true
